# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ueTmkmnQpLdc1U9FPveSrZnPotyE7FHH
"""



from mrjob.job import MRJob

from os import name
class Snow_days(MRJob):

    # Define a mapper function
    def mapper(self, key, line):

        # Use the `mapper` function to split each line in the CSV file on the comma
        [station, name, state, date, snow, tmax, tmin] = line.split(",")

        # Write a conditional statement to find the days it snowed.
        if snow and float(snow) > 0:
          yield date , 1

    # Use the `reducer` function to aggregate the total number of stations recording snow per date.
    def reducer(self, date, snow):
      yield date,sum(snow)

if __name__ == "__main__":
    Snow_days.run()



